# Generated by Django 5.2.6 on 2025-11-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('0.5kg', '½ Kg'), ('1kg', '1 Kg')], default='1kg', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(help_text='Price per selected unit'),
        ),
    ]
